-- Run this in your Supabase SQL Editor to create a profiles table
-- This table will store user name and username linked to their authentication record

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  name TEXT,
  email TEXT
);


-- ==========================================
-- APPOINTMENTS TABLE
-- ==========================================

CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL,
  patient_name TEXT NOT NULL,
  body_part TEXT NOT NULL,
  department TEXT NOT NULL,
  doctor_name TEXT NOT NULL,
  specialization TEXT,
  experience TEXT,
  fee TEXT,
  treatment TEXT,
  appointment_date DATE NOT NULL,
  time_slot TEXT NOT NULL,
  room TEXT,
  status TEXT DEFAULT 'Booked' NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Basic security: users can only see their own appointments
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own appointments" 
ON public.appointments FOR SELECT 
USING (auth.jwt() ->> 'email' = username OR username = auth.uid()::text);

-- In this app, 'username' in appointments table is currently stored as the user's email 
-- (see app.py line 269: st.session_state.username = lu where lu is email).
-- We'll allow insert if the user is authenticated.
CREATE POLICY "Users can insert their own appointments" 
ON public.appointments FOR INSERT 
WITH CHECK (true); 

CREATE POLICY "Users can update their own appointments" 
ON public.appointments FOR UPDATE 
USING (auth.jwt() ->> 'email' = username);


-- Basic security: allow users to read all profiles but only update their own
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);
